apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking

bases: []

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - vault.yaml
  - transaction.yaml
  - fraud.yaml
  - notification.yaml
  - frontend.yaml
  - ingress.yaml

configMapGenerator:
  - name: postgres-init-sql
    files:
      - init.sql=../infra/postgres/init.sql

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: banking-transaction-service
    newName: banking-transaction-service
  - name: banking-fraud-detection-service
    newName: banking-fraud-detection-service
  - name: banking-notification-service
    newName: banking-notification-service
  - name: banking-frontend
    newName: banking-frontend
